Add Vue example
mmckeaveney/theme-it pull request #11
Opened 2018-05-26 21:03 UTC by johman10

I found your help wanted tag on issue here: https://github.com/mmckeaveney/theme-it/issues/7

I figured to put myself on the Vue example and here is the PR related to it.
If you have any feedback on how I'm doing stuff in the example let me know.

I hope you like it. Let me know if you have any feedback. :)

2018-05-29 08:45 UTC, shogunpurple requested changes
Just a few minor comments. Great work, thank you so much for this PR! 🚀 Once the comments are addressed, I'll merge this 👍

2018-05-29 08:45 UTC, mmckeaveney commented on README.md
> +A basic Vue example of Theme It can be found here: https://codesandbox.io/s/zz2on366jl?view=preview
If you could just update this to be a link to your example that would be great. 

Like this - [Vue](https://codesandbox.io/s/zz2on366jl?view=preview)

2018-05-29 08:45 UTC, mmckeaveney commented on README.md
> +The examples are just as a showcase. Themeit doesn't, in any way, depend or the frameworks below.
typo

2018-06-08 09:16 UTC, johman10 commented
@mmckeaveney I changed the things you requested. Feel free to have another look and merge it when you feel like it's ready. :)

2018-06-08 09:32 UTC, shogunpurple approved these changes
LGTM. Thanks!

2018-06-08 09:32 UTC, merged